import type { Metadata } from "next";
import "./globals.css";
import Fv from "@/components/Fv";
import LineButton from "@/components/LineButton";
import Header from "@/components/Header";
import Artist from "@/components/Artist";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center bg-[url('/assets/images/bg.png')] bg-cover">
          <div className="flex-1 h-screen overflow-hidden max-xl:absolute max-xl:inset-0 max-xl:z-50 xl:sticky top-0 max-xl:animate-[fadeOut_8s_forwards]">
            <Fv />
            <div className="max-xl:hidden">
              <LineButton />
            </div>
          </div>
          <div className="w-[550px] xl:flex-[0_0_28.646vw] bg-white relative h-[20000px]">
            <Header />
            {children}
          </div>
          <div className="flex-1 max-lg:hidden">
            <Artist />
          </div>
        </div>
      </body>
    </html>
  );
}
