import type { Metadata } from "next";
import "./globals.css";
import Fv from "@/components/Fv";
import LineButton from "@/components/LineButton";
import Header from "@/components/Header";
import Artist from "@/components/Artist";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";
import Mainvisual from "@/components/Mainvisual";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center bg-[url('/assets/images/bg.png')] bg-cover">
          <Mainvisual />
          <div className="w-[550px] xl:flex-[0_0_28.646vw] bg-white relative">
            <Header />
            {children}
            <Footer />
          </div>
          <div className="flex-1 max-xl:hidden overflow-hidden">
            <Artist />
          </div>
        </div>
      </body>
    </html>
  );
}
