import type { Metadata } from "next";
import "./globals.css";
import Fv from "@/components/Fv";
import LineButton from "@/components/LineButton";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex bg-[url('/assets/images/bg.png')] bg-cover">
          <div className="flex-1 h-screen overflow-hidden sticky top-0">
            <Fv />
            <LineButton />
          </div>
          <div className="flex-[0_0_550px] bg-white relative h-[20000px]">
            <Header />
            {children}
          </div>
          <div className="flex-1"></div>
        </div>
      </body>
    </html>
  );
}
